replicaCount: 2

vault_url: https://kv0177.vault.azure.net/

image:
  repository: mypreciousacr.azurecr.io/todo
  pullPolicy: IfNotPresent
  tag: 6cd66997bc6cce4900b3610b33aae0d4faf4e9e0

db:
  user: master
  host: rg1mysql.mysql.database.azure.com
  name: todo
  port: 3306

service:
  port: 80

ingress:
  enabled: true

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
